---
title: "CUP Umaps"
author: "A.DeMartin"
date: "2025-03-17"
output: 
  html_document:
    keep_md: true
    toc: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
options(width = 100)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
seed <- 1234
```

## load packages
```{r load packages, warning=FALSE, include=FALSE}
library(ExploreSCdataSeurat3)
library(runSeurat3)
library(Seurat)
library(ggpubr)
library(pheatmap)
library(SingleCellExperiment)
library(dplyr)
library(tidyverse)
library(viridis)
library(muscat)
library(circlize)
library(destiny)
library(scater)
library(metap)
library(multtest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(DOSE)
library(grid)
library(gridExtra)
library(ggupset)
library(VennDiagram)
library(NCmisc)
```

## load file
```{r load merged file}
##load merged file 
fileNam <- "/Users/immbio/Desktop/Project/Angelina/CUP/data/CD45neg_allmerged_seurat.rds"
seuratM <- readRDS(fileNam)
table(seuratM$dataset)
table(seuratM$RNA_snn_res.0.25)
table(seuratM$orig.ident)
```

##set color vectors 
```{r set color vector}
coldiseaseCond <- c("#202547","#B45B5C")
names(coldiseaseCond) <- c("healthy", "CUP")
```

## plot umaps
```{r umap}
Idents(seuratM) <- seuratM$RNA_snn_res.0.25
DimPlot(seuratM, reduction = "umap", pt.size = 0.1) 

Idents(seuratM) <- seuratM$patient
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, shuffle = TRUE) 
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, split.by = "patient")

Idents(seuratM) <- seuratM$diseaseCond
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = coldiseaseCond, shuffle = TRUE) 

Idents(seuratM) <- seuratM$diseaseCond
coldiseaseCond <- c("#202547","lightgrey")
names(coldiseaseCond) <- c("healthy", "CUP")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = coldiseaseCond, order = "healthy") 

Idents(seuratM) <- seuratM$diseaseCond
coldiseaseCond <- c("lightgrey", "#B45B5C")
names(coldiseaseCond) <- c("healthy", "CUP")
DimPlot(seuratM, reduction = "umap", pt.size = 0.1, cols = coldiseaseCond, order = "healthy") 

coldiseaseCond <- c("#202547","#B45B5C")
names(coldiseaseCond) <- c("healthy", "CUP")
```

## calculate cluster marker genes
```{r marker genes, include=TRUE, eval=FALSE}
##cluster marker
Idents(seuratM) <- seuratM$RNA_snn_res.0.25
markerGenes <- FindAllMarkers(seuratM, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01)
#save table
write.table(markerGenes, 
            file= "/R/CUP/analysis/markerGenesRNA_snn_res.0.25",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)
```

## plot features cluster marker 
```{r feature plot marker genes}
##Immun
FeaturePlot(seuratM, features = "ENSG00000081237.PTPRC", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
##Endo
FeaturePlot(seuratM, features = "ENSG00000261371.PECAM1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000117707.PROX1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
##Fibroblastic
FeaturePlot(seuratM, features = "ENSG00000163359.COL6A3", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000107796.ACTA2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000164692.COL1A2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


##Tumor
FeaturePlot(seuratM, features = "ENSG00000205420.KRT6A", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM, features = "ENSG00000119888.EPCAM", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


```

```{r}
## Remove sample and filter the clusters

seuratMfil <- subset(seuratM, patient == ("hLN_01"), invert = TRUE) 


VlnPlot(seuratMfil, features = c("ENSG00000081237.PTPRC"), pt.size = 0, ncol = 4)

seuratM_stroma <- subset(seuratMfil, RNA_snn_res.0.25 %in% c("7","9","11","19"),invert = TRUE)


table(seuratMfil$patient)

Idents(seuratM_stroma) <- seuratM_stroma$RNA_snn_res.0.25
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1) 



```







```{r}

##rerun seurat
seuratM_stroma <- NormalizeData (object = seuratM_stroma)
seuratM_stroma <- FindVariableFeatures(object = seuratM_stroma)
seuratM_stroma <- ScaleData(object = seuratM_stroma, verbose = TRUE)
seuratM_stroma <- RunPCA(object=seuratM_stroma, npcs = 30, verbose = FALSE)
seuratM_stroma <- RunTSNE(object=seuratM_stroma, reduction="pca", dims = 1:20)
seuratM_stroma <- RunUMAP(object=seuratM_stroma, reduction="pca", dims = 1:20)
seuratM_stroma <- FindNeighbors(object = seuratM_stroma, reduction = "pca", dims= 1:20)

res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratM_stroma <- FindClusters(object = seuratM_stroma, resolution = res[i], random.seed = 1234)
}

Idents(seuratM_stroma) <- seuratM_stroma$RNA_snn_res.0.25
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1) 

Idents(seuratM_stroma) <- seuratM_stroma$patient
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1, shuffle = TRUE) 

Idents(seuratM_stroma) <- seuratM_stroma$diseaseCond
coldiseaseCond <- c("#202547","lightgrey")
names(coldiseaseCond) <- c("healthy", "CUP")
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1, cols = coldiseaseCond, order = "healthy") 


```

```{r feature plot marker genes}

##Endo
FeaturePlot(seuratM_stroma, features = "ENSG00000261371.PECAM1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000117707.PROX1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))

##Fibroblastic
FeaturePlot(seuratM_stroma, features = "ENSG00000163359.COL6A3", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000107796.ACTA2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000164692.COL1A2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


##Tumor
FeaturePlot(seuratM_stroma, features = "ENSG00000205420.KRT6A", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000119888.EPCAM", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


##Breast cancer cell marker
FeaturePlot(seuratM_stroma, features = "ENSG00000146648.EGFR", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000171345.KRT19", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000143546.S100A8", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000163220.S100A9", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


##Breast cancer cell marker
FeaturePlot(seuratM_stroma, features = "ENSG00000147889.CDKN2A", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))


```


```{r}

##cluster marker
Idents(seuratM_stroma) <- seuratM_stroma$RNA_snn_res.0.25
markerGenes_stroma <- FindAllMarkers(seuratM_stroma, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01)
#save table
write.table(markerGenes, 
            file= "/R/CUP/analysis/markerGenes_stroma",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)

```


```{r}


colclusterName <- c("#67001f", "#D53E4F", "#f4a582", "#FEE08B", "#003c30","#01665e","#66C2A5", "#3288BD","#BEAED4", "#c7eae5","#355C7D","#202547","#B45B5C")
names(colclusterName) <- c("FRC1","FRC2","Tu1","BEC1","CAF1","BEC2", "PRC","PRC_Tu","BEC3","Tu2","Tu3","LEC","PI16_FRC")



##assign celltypes
seuratM_stroma$colclusterName <- "stroma"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "0")] <- "FRC1"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "1")] <- "FRC2"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "2")] <- "Tu1"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "3")] <- "BEC1"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "4")] <- "CAF1"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "5")] <- "BEC2"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "6")] <- "PRC"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "7")] <- "PRC_Tu"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "8")] <- "BEC3"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "9")] <- "Tu2"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "10")] <- "Tu3"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "11")] <- "LEC"
seuratM_stroma$colclusterName[which(seuratM_stroma$RNA_snn_res.0.25 == "12")] <- "PI16_FRC"

table(seuratM_stroma$colclusterName)

Idents(seuratM_stroma) <- seuratM_stroma$colclusterName
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1, cols = colclusterName, label =TRUE) 


Idents(seuratM_stroma) <- seuratM_stroma$colclusterName
DimPlot(seuratM_stroma, reduction = "umap", pt.size = 0.1, cols = colclusterName, label =TRUE, split.by = "diseaseCond") 








```











```{r}

## Filter particular cell populations 

seuratM_fib_only <- subset(seuratM_stroma, colclusterName %in% c("FRC1","FRC2","PRC","PI16_FRC","CAF1","PRC_Tu")) 


##cluster marker
Idents(seuratM_fib_only) <- seuratM_fib_only$colclusterName
markerGenes_Fib <- FindAllMarkers(seuratM_fib_only, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01)
#save table
write.table(markerGenes, 
            file= "/R/CUP/analysis/markerGenes_Fib",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)


```


```{r}

FeaturePlot(seuratM_stroma, features = "ENSG00000166923.GREM1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM_stroma, features = "ENSG00000162493.PDPN", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))

FeaturePlot(seuratM_stroma, features = "ENSG00000133110.POSTN", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000078098.FAP", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000172061.LRRC15", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
	

FeaturePlot(seuratM_stroma, features = "ENSG00000174059.CD34", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_stroma, features = "ENSG00000143196.DPT", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
	



```


## dotplot marker genes
```{r dotplot marker genes, fig.height=8, fig.width=8}
seuratM_stroma$colclusterName <- factor(seuratM_stroma$colclusterName, levels=c("PI16_FRC","FRC1","FRC2", "PRC","PRC_Tu","CAF1","Tu1","Tu2","Tu3","BEC1","BEC2","BEC3","LEC"))
Idents(seuratM_stroma) <-seuratM_stroma$colclusterName

genes <- data.frame(gene=rownames(seuratM_stroma)) %>% 
  mutate(geneID=gsub("^.*\\.", "", gene))

selGenes <- data.frame(geneID=rev(c( "COL1A2", "COL6A3", "PDGFRB", "DCN",  "FBN1", "C7", "CCL21","CCL19", "CXCL12", "PI16", "ACTA2", "ITGA7","RGS5", "NOTCH3", "MCAM","PDPN", "FAP","LRRC15","POSTN","PECAM1", "VWF", "EGFL7", "ITGA10", "PROX1"))) %>% left_join(., genes, by="geneID") %>% filter(gene != "ENSG00000232995.RGS5") 

DotPlot(seuratM_stroma, features = selGenes, group.by= "colclusterName") + RotatedAxis() + scale_color_viridis(option="F") + coord_flip()


```


## rel abundance
```{r rel abundance, fig.height=8, fig.width=8}
###dataset
datList <- NULL
for(con in unique(seuratM_stroma$patient)){
  seuratSub <- subset(seuratM_stroma, patient==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$colclusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(patient=con)
  datList[[con]] <- dat_con
}
dat_all <- do.call("rbind", datList)

## plot abundance
ggbarplot(dat_all, x= "patient", y= "percent", fill = "Var1",  legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

###cond
###patient_diseaseCond
datList <- NULL
for(con in unique(seuratM_stroma$diseaseCond)){
  seuratSub <- subset(seuratM_stroma, diseaseCond==con)
  print(dim(seuratSub))
  dat_con <- as.data.frame(table(seuratSub$colclusterName)) %>%
  mutate(percent=Freq/ncol(seuratSub)) %>% mutate(diseaseCond=con)
  datList[[con]] <- dat_con
}

dat_all <- do.call("rbind", datList)

##ordpatient_diseasecond <- unique(seuratMfil$patient_diseaseCond)[order(
 ## !grepl("healthy", unique(seuratMfil$patient_diseaseCond)),  # "HH" first (FALSE is sorted before TRUE)
 ## !grepl("visit1", unique(seuratMfil$patient_diseaseCond)),  # "visit1" second
 ## !grepl("visit2", unique(seuratMfil$patient_diseaseCond)),  # "visit2" third
 ## !grepl("visit3", unique(seuratMfil$patient_diseaseCond)),  # "visit3" third
 ## !grepl("visit4", unique(seuratMfil$patient_diseaseCond)),  # "visit4" third
 ## !grepl("visit5", unique(seuratMfil$patient_diseaseCond)),  # "visit5" third
 ## !grepl("visitX1", unique(seuratMfil$patient_diseaseCond)),  # "visitX1" third
 ## !grepl("visitX2", unique(seuratMfil$patient_diseaseCond)),  # "visitX2" third
 ##  !grepl("visitX3", unique(seuratMfil$patient_diseaseCond)),  # "visitX3" third
 ## unique(seuratMfil$patient_diseaseCond)  # Alphabetical order within groups
##)]

## plot abundance
ggbarplot(dat_all, x= "diseaseCond", y= "percent", fill = "Var1", palette = colclusterName, legend = "right", legend.titel = "cluster", ylab = "frequency")  + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 






```


```{r}
## Filter the gene list from marker genes (Top200 genes filtered with adj P value and avg_log2FC)

top200_by_cluster <- markerGenes_Fib %>%
  filter(p_val_adj < 0.05) %>%                  # Filter for significant genes
  group_by(cluster) %>%
  arrange(desc(abs(avg_log2FC))) %>%           # Rank by effect size
  slice_head(n = 200) %>%                      # Take top 200 per cluster
  mutate(EnsID=gsub("\\..*","", gene))%>%
  ungroup()


top200_split <- top200_by_cluster %>%
  group_by(cluster) %>%
  group_split()

# Named list for clarity
names(top200_split) <- sapply(top200_split, function(x) unique(x$cluster))

# Perform enrichGO on each cluster's top 200 genes
ego_list <- map(top200_split, function(df) {
  enrichGO(
    gene          = unique(df$EnsID),
    OrgDb         = org.Hs.eg.db,
    keyType       = 'ENSEMBL',
    ont           = "BP",
    pAdjustMethod = "BH",
    pvalueCutoff  = 0.05,
    qvalueCutoff  = 0.05
  ) %>% setReadable(OrgDb = org.Hs.eg.db)
})



# Combine all cluster results into a single data frame
combined_results <- bind_rows(
  lapply(names(ego_list), function(name) {
    result <- ego_list[[name]]
    if (!is.null(result) && nrow(result@result) > 0) {
      df <- result@result
      df$cluster <- name  # Add cluster name as a column
      return(df)
    }
    NULL  # Skip if empty or NULL
  })
)

# Write combined results to one txt file
write.table(combined_results, file = "GO_combined_top200.txt",
            sep = "\t", row.names = FALSE, quote = FALSE)







```

```{r plot gene signature onto umap}
##convert seurat object to sce object
sce <- as.SingleCellExperiment(seuratM_stroma)

##define genes
ECMorganization <- data.frame(gene=c("MMP13","MMP1","MMP7","KLK4","COL11A1","MMP11","SFRP2","DPP4","COL8A1","COL10A1","FAP","POSTN","LAMA1"))


##define signature for FRCs
CAF1 <- data.frame(gene=c("GREM1", "PDPN", "POSTN", "FAP", "LRRC15"))


genes <- data.frame(geneID=rownames(sce)) %>% mutate(gene=gsub(".*\\.", "", geneID))

## color palette 
library(RColorBrewer)
#pal = colorRampPalette(rev(brewer.pal(11, "RdBu")))
pal = colorRampPalette(c("#053061", "#2166ac", "#f7f7f7", "#f4a582", "#b2183c", "#85122d"))
sc <- scale_colour_gradientn(colours = pal(100), limits=c(0, 2.5))
#sf <- scale_fill_gradientn(colours = pal(100), limits=c(0, 5))

##make a count matrix of signature genes
signGenes <- genes %>% dplyr::filter(gene %in% CAF1$gene)
sceSub <- sce[which(rownames(sce) %in% signGenes$geneID),]
cntMat <- rowSums(t(as.matrix(
    sceSub@assays@data$logcounts)))/nrow(signGenes)

sceSub$sign <- cntMat

sceSub$sign2 <- sceSub$sign
sceSub$sign2[which(sceSub$sign > 2.5)] <- 2.5

plotUMAP(sceSub, colour_by = "sign2", point_size = 1) + sc + theme(legend.position = "none")

##check max and min values
max(sceSub$sign)
## check missing genes
check <- OxidativePhosphorilation %>% filter(!OxidativePhosphorilation$gene %in% signGenes$gene)

```

```{r}

signatures <- list(
  CAF1 = c("GREM1", "PDPN", "POSTN", "FAP", "LRRC15"),
  FRC = c("CCL19", "CCL21", "DPT","COL1A2", "IL33", "DES"),
  PRC = c("RGS5", "MCAM", "NOTCH3", "FABP4", "ESAM")
)


# Extract gene symbols
genes <- data.frame(geneID = rownames(sce)) %>%
  mutate(gene = gsub(".*\\.", "", geneID))

# Function to compute signature and return UMAP plot
plot_signature_umap <- function(sig_name, sig_genes) {
  signGenes <- genes %>% filter(gene %in% sig_genes)
  sceSub <- sce[rownames(sce) %in% signGenes$geneID, ]
  
  cntMat <- rowSums(t(as.matrix(sceSub@assays@data$logcounts))) / nrow(signGenes)
  sceSub$sign <- cntMat
  sceSub$sign2 <- pmin(sceSub$sign, 2.5)  # cap at 2.5
  
  plotUMAP(sceSub, colour_by = "sign2", point_size = 1) +
    scale_color_viridis_c() +  # or another color scale
    ggtitle(paste0(sig_name, " signature")) +
    theme_minimal() +
    theme(legend.position = "right")
}

# Generate all plots
umap_plots <- lapply(names(signatures), function(name) {
  plot_signature_umap(name, signatures[[name]])
})

# Optionally: show all plots (in interactive session or PDF)
# Print them one by one
for (p in umap_plots) print(p)




```






```{r}


egoFib <- enrichGO(gene = unique(top200_by_cluster$EnsID),
                          OrgDb = org.Hs.eg.db,
                          keyType = 'ENSEMBL',
                          ont = "BP",
                          pAdjustMethod = "BH",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)
egoFib <- setReadable(egoFib, OrgDb = org.Hs.eg.db)

print(egoFib@result)

write.table(egoFib@result, file = "egoFib_results.txt", sep = "\t", row.names = FALSE, quote = FALSE)



```





```{r}
### save seurat object
saveRDS(seuratM_stroma, file="/R/CUP/data/Stroma_allmerged_seurat.rds")


```




```{r}
## Filter particular cell populations 

seuratM_fib <- subset(seuratM, RNA_snn_res.0.25 %in% c("0","2","3","8","18")) 


##rerun seurat
seuratM_fib <- NormalizeData (object = seuratM_fib)
seuratM_fib <- FindVariableFeatures(object = seuratM_fib)
seuratM_fib <- ScaleData(object = seuratM_fib, verbose = TRUE)
seuratM_fib <- RunPCA(object=seuratM_fib, npcs = 30, verbose = FALSE)
seuratM_fib <- RunTSNE(object=seuratM_fib, reduction="pca", dims = 1:20)
seuratM_fib <- RunUMAP(object=seuratM_fib, reduction="pca", dims = 1:20)
seuratM_fib <- FindNeighbors(object = seuratM_fib, reduction = "pca", dims= 1:20)

res <- c(0.25, 0.6, 0.8, 0.4)
for (i in 1:length(res)) {
  seuratM_fib <- FindClusters(object = seuratM_fib, resolution = res[i], random.seed = 1234)
}

Idents(seuratM_fib) <- seuratM_fib$RNA_snn_res.0.25
DimPlot(seuratM_fib, reduction = "umap", pt.size = 0.1) 

Idents(seuratM_fib) <- seuratM_fib$patient
DimPlot(seuratM_fib, reduction = "umap", pt.size = 0.1, shuffle = TRUE) 

Idents(seuratM_fib) <- seuratM_fib$diseaseCond
coldiseaseCond <- c("#202547","lightgrey")
names(coldiseaseCond) <- c("healthy", "CUP")
DimPlot(seuratM_fib, reduction = "umap", pt.size = 0.1, cols = coldiseaseCond, order = "healthy") 


```


```{r}

##Fibroblastic
FeaturePlot(seuratM_fib, features = "ENSG00000172724.CCL19", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000156234.CXCL13", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000162493.PDPN", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000137573.SULF1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000133110.POSTN", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000166923.GREM1", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000180875.GREM2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))
FeaturePlot(seuratM_fib, features = "ENSG00000107796.ACTA2", pt.size = 0.5, cols = c("lightgrey", "#BE3144"))



```

```{r}

##cluster marker
Idents(seuratM_fib) <- seuratM_fib$diseaseCond
markerGenes <- FindAllMarkers(seuratM_fib, only.pos=T) %>% 
  dplyr::filter(p_val_adj < 0.01)
#save table
write.table(markerGenes, 
            file= "/R/CUP/analysis/markerGenes_diseaseCond",
            sep="\t",
            quote=F,
            row.names=F,
            col.names=T)



```


```{r}

VlnPlot(seuratM_fib, features = c("ENSG00000107796.ACTA2"),group.by = "diseaseCond", pt.size = 0, ncol = 4)
VlnPlot(seuratM_fib, features = c("ENSG00000133110.POSTN"),group.by = "diseaseCond", pt.size = 0, ncol = 4)
VlnPlot(seuratM_fib, features = c("ENSG00000172724.CCL19"),group.by = "diseaseCond", pt.size = 0, ncol = 4)


```


```{r save merged seurat object, eval=FALSE, include=TRUE}
### save seurat object
saveRDS(seuratM_fib, file="/R/CUP/data/Fib_allmerged_seurat.rds")
```



## session info
```{r date and session info}
date()
sessionInfo()
```
